### ISSUE TITLE
[Question] Background info

### ISSUE THREAD

**Issue by ShortDevelopment** [Pdawg-bytes/hwnd-xamlpresenter-notepad#1]
Hey, I just found your intresting little project!

I'm interested: Where did you get that `*.winmd` from?
I sadly could not consume it directly using `dotnet core 3.0` but I could use the individual interfaces...

Do you happen to know on which Windows-Versions `XamlPresenter` is supported?

It seems like you still need an existing `Windows.UI.Xaml.Application` singleton instance.
Having that in mind, it could be a nice replacement for XamlIslands!

**Comment by Pdawg-bytes** [comment]
Hey! I got the WinMD from ADeltaX's WinMD repo, (https://github.com/ADeltaX/InternalWinMD). XamlPresenter should work on any version of windows that supports xaml islands (this is only a guess, I'm not really sure).

**Comment by ShortDevelopment** [comment]
Thanks!
I’m working on different scenarios of XamlIsland as WinUI3 seems to be relatively unstable for now…
